### ISSUE TITLE
calculating the average lapse rate between this level and all higher levels within 2 kilometers does not exceed 2 deg K?

### ISSUE THREAD

**Issue by linlintamu** [robertej09/tropopauseCalc#1]
Hello,

When I looked into the codes in wmo.py, I found something that I cannot understand well. Probably I miss something and I would like to confirm.

Near the end of the bulk code in wmo.py, we try to calculate the average lapse rate between this level and all higher levels within 2 kilometers and determine this average lapse rate does not exceed 2 deg K.
Within the iLev and nLevm loop, we do not assign new values to "lapseSum" and "lapseAvg" will always be zero.

I guess it should be lapseSum = lapseSum + lapse[L] rather than lapseAvg = lapseSum + lapse[L].

Thanks,
Lin

**Comment by ana-v-espinoza** [comment]
Hey Lin,

Thanks for taking a look at our code. It seems like that was a typo that we missed. Feel free to submit a pull request, or I can make the fix myself if you'd like. To clarify, you're referring to [this](https://github.com/robertej09/tropopauseCalc/blob/main/wmo.py#L51) line, correct?

Best,
A

**Comment by linlintamu** [comment]
Hello again,

After I fix the "lapseSum" bug in the wmo.py, there is another thing I cannot understand well.
When first attempt to determine pTrop, a weight is calculated as a function of lapse rates at two adjacent levels around iLev, i.e., weight = (lapseC-lapse[iLev])/(lapse[iLev+1]-lapse[iLev]). 

What is the reason to calculate this weight?
Probably most of the time, the calculation of weight in this way works fine.

Have you ever encountered a situation where the difference of lapse[iLev+1] and lapse[iLev] is tiny, leading to a very large weight value and unreasonable pTrop...
For example, when using the sounding data on 2015/5/30 at 12 at station "AMA". You can try and you will end up with a pTrop of 1087 mb...

Sorry. I do not mean to criticize your code. Instead, I much appreciate your input! I just pick a random day to test your code and run into troubles unexpectedly. 
 
Thanks,
Lin

**Comment by ana-v-espinoza** [comment]
Hey,

No problem whatsoever, I appreciate the scrutiny! We had plans to test the code using a larger number of soundings but the project was basically abandoned.

The weight is an intermediate step in linearly interpolating the pressure between the point where the lapse rate falls below the 2K/km value as in the WMO definition of tropopause pressure:

WMO (1992): International meteorological vocabulary, Genf, 784pp.:

       The first tropopause is defined as the lowest level at which
       the lapse rate decreases to 2 deg K per kilometer or less,
       provided also the average lapse rate between this level and
       all higher levels within 2 kilometers does not exceed 2 deg K.

See the attached PDF for a quick derivation. 
[tropopauseCalc_pressureInterpolation.pdf](https://github.com/robertej09/tropopauseCalc/files/8374749/tropopauseCalc_pressureInterpolation.pdf)

The wmo.py file was specifically written to implement the Fortran implementation for calculating the tropopause in the NCL, found [here](https://github.com/NCAR/ncl/blob/develop/ni/src/lib/nfpfort/stattrop_dp.f), and is a lot better documented!

With regards to your test (May 30, 2015 at 12z), I get the same result of "WMO: 1087 millibar" when running testTropCalc.py on the raw data. However, when that data is interpolated to a larger number of points (I believe we did this to simulate higher frequency sounding data), the result is "WMO: (interp) 95 millibar," which is similar to what is found using the "coldest point" method or what is expected from visual inspection of the sounding.

I'm not sure whether this points towards another bug in the code or whether the WMO method itself can't handle this case well. The best way to check whether the code is "right" would be to compare this output to that given by the NCL function (linked above).

Let me know if there's any way I can help.

**Comment by linlintamu** [comment]
Thank you very much for your explanation which helps a lot. 
But I also think that it is this underlying mathematics and this way of calculating weight that cause the unreasonable pTrops (either too large or too small...) if there is any. It might be the inherent limitation of this method I guess (I haven't had a chance to read more literature to learn more). I tested a relatively large number of soundings and found sometimes the absolute values of weight are too large (either too postive or too negative), resulting from "extrapolation" instead of "interpolation".

I have a few ideas that could make the code maybe better and they are what I did to make your code more "feasible" in my cases.
(1) I clean the data first. The soundings downloaded or read from University of Wyoming sometimes have duplicated pressure values. Recall that in wmo.py, we calculate lapse[iLev] = const*np.log(TFull[iLev]/TFull[iLev+1])/np.log(pFull[iLev]/pFull[iLev+1]). in the denominator, we might encounter division by zero. So, remove the duplicated pressure values and all the other information in the same row first to remove the warnings in python.

(2) I put a constraint on pTrop when it is determined from the "interpolation". If the resulting pTrop is unreasonable, I simply assign pTrop as pHalf[iLev].

(3) fix the "lapseSum" typo.

(4) I put a "break" to terminate the iLev loop from 0 to nlem-1 when "found" becomes True under the (if not found) else condition, in order to save some computational time. 
When "found" becomes True, even though it will not hit the if lapse[iLev] < lapseC and pFull[iLev] < pMax and not found condition again, it still loops to the very top altitudes (for iLev in range(0,nLevm-1):) but does nothing. As soon as pTrop is settled down, "break" the loop.

When testing your code, I did study the Fortran code written for NCL. And I believe that your python code agrees well with what the Fortran code did. After fixing the "lapseSum" typo, there should be no other errors to my knowledge.

Thanks,
Lin

**Comment by ana-v-espinoza** [comment]
Hey,

Those all sound like great additions and changes. Like I had mentioned, feel free to fork the repo and submit a Pull Request, since you seem to have already done some of the work to make these changes. If you would like help learning how to do so I can point you in the right direction. If you can get this into a state that you feel is "research ready" we could even consider submitting a PR to the main metpy repository! I'm sure they'd appreciate your contributions as much as I have.
