### ISSUE TITLE
lapseAvg calculation in wmo.py

### ISSUE THREAD

**Issue by joleenf** [robertej09/tropopauseCalc#2]
Hi Ana,

Should the assignment to `lapseAvg` in this line
https://github.com/ana-v-espinoza/tropopauseCalc/blob/29535fdfaa88532f06a7c3463e02548fef1d46d3/wmo.py#L51

instead be
`lapseSum = lapseSum + lapse[L]`

which matches
https://github.com/NCAR/ncl/blob/8a96101fe14d0cf0f5ed66a5e6b1733084bc69df/ni/src/lib/nfpfort/stattrop_dp.f#L196

Thank-you for working on this.

**Comment by ana-v-espinoza** [comment]
Hey Joleen,

Thanks for the comment! This is indeed something that has been brought to my attention in a previous issue, however this repository has not been a priority of mine for the last three years and in fact had its inception as a homework assignment!

While I'll make the correction, I do not plan on continuing this work any time soon, although you or anybody you know is more than welcome to pick this back up.

Thank you,

Ana V. E.

**Comment by ana-v-espinoza** [comment]
Addressed by #3
